/** @type {import('tailwindcss').Config} */
module.exports = {
  darkMode: "class",
  content: [
    "./*.html",
    "./*.js",
    "./docs/**/*.html",
  ],
  theme: {
    extend: {
      colors: {
        "primary":                    "#001e4b",
        "primary-container":          "#0a3270",
        "primary-hi":                 "#1a5aaa",
        "on-primary":                 "#ffffff",
        "on-primary-container":       "#dce8ff",
        "accent":                     "#e1000f",
        "accent-container":           "#ff3322",
        "on-accent":                  "#ffffff",
        "surface":                    "#F2F0EC",
        "surface-container-lowest":   "#FAFAF9",
        "surface-container-low":      "#ECEAE5",
        "surface-container":          "#E2DFD9",
        "surface-container-high":     "#D5D2CB",
        "surface-dim":                "#C6C3BB",
        "background":                 "#F2F0EC",
        "inverse-surface":            "#001e4b",
        "inverse-surface-mid":        "#0a2d5e",
        "inverse-surface-soft":       "#1a4080",
        "inverse-on-surface":         "#F1F5F9",
        "on-surface":                 "#111827",
        "on-background":              "#111827",
        "secondary":                  "#4B5563",
        "on-surface-variant":         "#6B7280",
        "tertiary":                   "#1A9850",
        "tertiary-container":         "#25D366",
        "on-tertiary":                "#ffffff",
        "on-tertiary-container":      "#003b15",
        "outline":                    "#9CA3AF",
        "outline-variant":            "#D1D5DB",
        "surface-variant":            "#E2DFD9",
        "surface-container-highest":  "#D5D2CB",
        "secondary-container":        "#ECEAE5",
        "on-secondary-container":     "#1F2937",
        "error":                      "#ba1a1a",
        "on-error":                   "#ffffff",
        "error-container":            "#ffdad6",
        "inverse-primary":            "#1a5aaa",
        "surface-tint":               "#0a3270",
        "primary-fixed":              "#dce8ff",
        "on-secondary-fixed":         "#111827",
        "surface-bright":             "#FAFAF9",
        "on-secondary":               "#ffffff",
        "tertiary-fixed":             "#7ffc97",
        "tertiary-fixed-dim":         "#62df7d",
        "on-tertiary-fixed":          "#002109",
        "on-tertiary-fixed-variant":  "#005320",
      },
      fontFamily: {
        "headline": ["Space Grotesk", "sans-serif"],
        "body":     ["Inter", "sans-serif"],
        "label":    ["Inter", "sans-serif"],
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg":      "0.25rem",
        "xl":      "0.5rem",
        "2xl":     "0.75rem",
        "full":    "0.75rem",
      },
    },
  },
  plugins: [
    require("@tailwindcss/forms"),
  ],
}
